typography_spectrum: 0.4551971
color:
  saturation: 0.4749104
  brandStrength: 1
  lightness: 0.4964158
  brandColors:
    - '#030206'
    - '#FCFCFF'
    - '#FBB3AD'
    - '#A2A3C6'
    - '#392992'
  rhythmicContrast: 1
layout_spectrum: 0.5017921
author:
  name: Maurice
  email: info@mauricevanlier.com
  url: www.mauricevanlier.com
logo: null
name: Maurice van Lier
navigation:
  - name: About
    id: 8e0c6592-77d0-4ec1-a4a6-435ca252a958
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Artist
